version: "3.8"
services:
  # API: mongo 127.0.0.1:1545
  # golang-api:
  #   build: ./
  #   command: go run main.go
  #   container_name: immria-api
  #   networks:
  #     - immria
  #   ports:
  #     - '1545:1545'
  #   restart: unless-stopped
    # volumes:
    #   - ../../assets:/app/assets:
  # CLI: mongo 127.0.0.1:27017
  mongo-db:
    container_name: mongo-db
    image: mongo:6.0.3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - mongodb-network
    ports:
      - ${MONGO_INITDB_EXTERNAL_PORT}:27017
    volumes:
      - mongodb-data:/data/db
  # UI: http://127.0.0.1:8081
  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    depends_on:
      - mongo-db
    networks:
      - mongodb-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-db
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
    ports:
      - ${ME_CONFIG_EXTERNAL_PORT}:8081
    volumes:
      - mongodb-data
volumes:
  mongodb-data:
    name: mongodb-data
networks:
  mongodb-network:
    external: true